  api-version: 1.16
  name: ResetWorldBlocks
  main: main.ResetWorldBlocks
  version: '0.1'
  author: Santres
  commands:
    resetblocks:
      description: "Reset all the broken and placed blocks in the world."
      usage: "/<command>"